# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-16 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='organization/teachers/default.png', max_length=128, upload_to='organization/teahers/%Y/%m', verbose_name='讲师照片'),
        ),
    ]
