# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-14 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='course/default.png', max_length=128, upload_to='course/%Y/%m', verbose_name='课程封面'),
        ),
    ]
